
// Generated by /home/mpr/google/qfs/src/cc/common/buildversgit.sh. Do not edit.

#include "Version.h"
#include "hsieh_hash.h"

namespace KFS {

const std::string KFS_BUILD_INFO_STRING=
"KFS_BUILD_INFO_START\n"
"host: fb01\n"
"user: mpr\n"
"date: Tue Apr 19 18:13:30 CST 2016\n"
"build type: Debug\n"
"boost: /usr/include /usr/lib/x86_64-linux-gnu/libboost_regex.so\n"
"source dir: /home/mpr/google/qfs\n"
"release: 1.1.4\n"
"git config:\n"
"user.name=wqx081\n"
"user.email=wangqx@mpreader.com\n"
"core.repositoryformatversion=0\n"
"core.filemode=true\n"
"core.bare=false\n"
"core.logallrefupdates=true\n"
"remote.origin.url=https://github.com/quantcast/qfs\n"
"remote.origin.fetch=+refs/heads/*:refs/remotes/origin/*\n"
"branch.master.remote=origin\n"
"branch.master.merge=refs/heads/master\n"
"git status:\n"
"git branch:\n"
"* master 1b6a93e4b7fd84170c3d6b3bd8be353620b51cdf webui: remove executable flag from gif files\n"
"git remote:\n"
"origin	https://github.com/quantcast/qfs (fetch)\n"
"origin	https://github.com/quantcast/qfs (push)\n"
"version:\n"
"https://github.com/quantcast/qfs/master@1b6a93e4b7fd84170c3d6b3bd8be353620b51cdf\n"
"KFS_BUILD_INFO_END\n"
;

static std::string MakeVersionHash()
{
    Hsieh_hash_fcn f;
    unsigned int h = (unsigned int)f(KFS_BUILD_INFO_STRING);
    std::string ret(2 * sizeof(h), '0');
    for (size_t i = ret.length() - 1; h != 0; i--) {
        ret[i] = "0123456789ABCDEF"[h & 0xF];
        h >>= 4;
    }
    return ret;
}

const std::string KFS_BUILD_VERSION_STRING(
    std::string("1.1.4-1b6a93e4b7fd84170c3d6b3bd8be353620b51cdf-Debug-") +
    MakeVersionHash()
);

const std::string KFS_SOURCE_REVISION_STRING(
    "1.1.4-https://github.com/quantcast/qfs/master@1b6a93e4b7fd84170c3d6b3bd8be353620b51cdf"
);

}

